version: '3'
volumes:
  dados:
networks:
  banco:
  web:
  fila:
services:
  db:
    image: postgres:9.6.16
    volumes:
      - dados:/var/lib/postgresql/data # Volume dos dados
      - ./scripts:/scripts # Scripts -> inside the container to /script
      # It means that this Database belongs to the "banco" network
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - banco
  frontend:
    image: nginx:1.13
    volumes:
      - ./web:/usr/share/nginx/html/ # Site
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf # Reverse Proxy Configuration
    ports:
      - 80:80
    networks: # It means that this Frontend belongs to the "web" network
      - web
    depends_on:
      - app
  app:
    image: python:3.6
    volumes:
      - ./app:/app # Application
    working_dir: /app
    command: bash ./app.sh
    networks:
      - banco
      - web
      - fila
    depends_on:
      - db
      - queue
    environment:
      - DB_NAME=[ERRO]{INVALIDO}asdasddsadas_sender
      
  queue:
    image: redis:3.2
    networks:
      - fila
  worker:
    build: worker
    volumes: 
      - ./worker:/worker # Worker
    working_dir: /worker
    command: worker.py
    networks:
      - fila
    depends_on:
      - queue